    <!-- Page Footer -->
        <footer class="section" id="footer" role="contentinfo">
            <div class="container">
                <div class="row-fluid">
                    <div class="span4">
                        <h3>Contact</h3>
                        <p>
                          7 rue des Saints Pères<br />75006 Paris<br />
                          France
                        </p>
                        <ul class="icons">
                            <li>
                                <i class="icon-envelope"></i>
                                <a href="mailto:me@geraldplusquellec.me">Courriel</a>
                            </li>
                            <li>
                                <i class="icon-phone"></i>
                                <a href="#" onclick="return false" target="_blank">+ 33 6 72 87 35 58</a>
                            </li>
                            <li>
                                <i class="icon-linkedin-sign"></i>
                                <a href="http://www.linkedin.com/profile/view?id=26488376" target="_blank">gplusquellec</a>
                            </li>
                        </ul>
                    </div>
                    <div class="span4">
                        <h3>services</h3>
                        <ul class="icons">
                            <li>
                                <i class="icon-ok"></i>
                                <a href="<?php urlsite(); ?>services/web">Création site internet</a>
                            </li>
                            <li>
                                <i class="icon-ok"></i>
                                <a href="<?php urlsite(); ?>services/ecommerce">Commerce en ligne</a>
                            </li>
                            <li>
                                <i class="icon-ok"></i>
                                <a href="<?php urlsite(); ?>services/content">Gestionnaire de contenu</a>
                            </li>
                            <li>
                                <i class="icon-ok"></i>
                                <a href="<?php urlsite(); ?>services/refonte">Refonte de site</a>
                            </li>
                            <li>
                                <i class="icon-ok"></i>
                                <a href="<?php urlsite(); ?>services/vitrine">Site vitrine</a>
                            </li>
                        </ul>
                    </div>
                    <div class="span4">
                        <h3>plan du site</h3>
                        <ul class="icons">
                            <li>
                                <i class="icon-home"></i>
                                <a href="<?php urlsite(); ?>">Accueil</a>
                            </li>
                            <li>
                                <i class="icon-tasks"></i>
                                <a href="<?php urlsite(); ?>services">Services</a>
                            </li>
                            <li>
                                <i class="icon-envelope"></i>
                                <a href="<?php urlsite(); ?>contact">Contact</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12 pull-center" style='font-size: 80%;'>&copy; 1996 - <?php echo date('Y'); ?> GP</div>
                </div>
            </div>
        </footer>
        <a href="#" class="scrollup"><i class="icon-chevron-up icon-square icon-32 active"></i></a>
        <script src="<?php urlsite(); ?>assets/js/jquery.min.js" type="text/javascript"></script>
        <script src="<?php urlsite(); ?>assets/js/bootstrap.js" type="text/javascript"></script>
        <script src="<?php urlsite(); ?>assets/js/script.js" type="text/javascript"></script>
        <script type="text/javascript">
            if (typeof gaJsHost == 'undefined') {
                var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
                document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
            }
        </script>
    </body>
</html>
