<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8] -->
<html lang="fr">
<!-- <![endif] -->
    <head>
        <meta charset="utf-8" />
        <!-- %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"} -->
        <title>Gérald Plusquellec - <?php echo $this->title; ?></title>
        <meta content="freelance web depuis 1996" name="description" />
        <meta content="GP Framework" name="generator" />
        <meta content="Gérald Plusquellec" name="author" />
        <meta content="width=device-width, initial-scale=1.0" name="viewport" />
        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <link href="<?php urlsite(); ?>assets/img/gp.gif" rel="shortcut icon" />
        <link href="<?php urlsite(); ?>assets/img/apple-touch-icon-114x114-precomposed.png" rel="apple-touch-icon-precomposed" sizes="114x114" />
        <link href="<?php urlsite(); ?>assets/img/apple-touch-icon-72x72-precomposed.png" rel="apple-touch-icon-precomposed" sizes="72x72" />
        <link href="<?php urlsite(); ?>assets/img/apple-touch-icon-57x57-precomposed.png" rel="apple-touch-icon-precomposed" />
        <link href="<?php urlsite(); ?>assets/css/bootstrap.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?php urlsite(); ?>assets/css/responsive.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?php urlsite(); ?>assets/css/font-awesome.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?php urlsite(); ?>assets/css/theme.css" media="screen" rel="stylesheet" type="text/css" />
        <link href="<?php urlsite(); ?>assets/css/fonts.css" media="screen" rel="stylesheet" type="text/css" />
    </head>
    <body class="theme-pattern-lightmesh">
        <!-- Page Header -->
        <header id="masthead">
            <nav class="navbar navbar-fixed-top">
                <div class="navbar-inner">
                    <div class="container">
                        <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </a>
                        <h1 class="brand">
                            <a href="<?php urlsite(); ?>">
                                Gérald Plusquellec
                                <i class="icon-cogs"></i>
                            </a>
                        </h1>
                        <div class="nav-collapse collapse">
                            <ul class="nav pull-right">
                                <li class="<?php echo $this->activeHome; ?>"><a href="<?php urlsite(); ?>">Accueil</a></li>
                                <li id="servicesMenu" class="dropdown <?php echo $this->activeServices; ?>">
                                    <a class="dropdown-toggle" href="#" data-toggle="dropdown">Services <span class="caret"></span></a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <a href="<?php urlsite(); ?>services/web">Création site internet</a>
                                        </li>
                                        <li>
                                            <a href="<?php urlsite(); ?>services/ecommerce">Commerce en ligne</a>
                                        </li>
                                        <li>
                                            <a href="<?php urlsite(); ?>services/content">Gestionnaire de contenu</a>
                                        </li>
                                        <li>
                                            <a href="<?php urlsite(); ?>services/refonte">Refonte de site</a>
                                        </li>
                                        <li>
                                            <a href="<?php urlsite(); ?>services/vitrine">Site vitrine</a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="<?php echo $this->activeContact; ?>"><a href="<?php urlsite(); ?>contact">Contact</a></li>
                                <li><a rel="tooltip" title="Travail sur Github" href="https://github.com/schpill/thin" target="_blank"><i class="icon-github huge-icon"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </nav>
        </header>
