<?php includes('partials/header/classic.phtml'); ?>
<!-- Main Content -->
    <div id="content" role="main">
        <section class="section alt" id="promo">
            <div class="map-top-shadow"></div>
                <div id="map"></div>
            <div class="map-bottom-shadow"></div>
        </section>
        <section class="section">
            <div class="container">
                <div class="page-header">
                    <h1>
                        Contactez-moi
                        <small>Un projet ? une question ? ou par simple curiosité&hellip;</small>
                    </h1>
                </div>
                <div class="row-fluid">
                    <div class="span6 span-false">
                        <ul class="icons">
                            <li>
                                <p>
                                    <i class="icon-home"></i>7 rue des Saints Pères 75006 Paris
                                </p>
                            </li>
                            <li>
                                <p>
                                    <i class="icon-phone"></i>+ 33 1 83 62 85 72
                                </p>
                            </li>
                            <li>
                                <p>
                                    <i class="icon-envelope"></i><a href="mailto:me@geraldplusquellec.me">me@geraldplusquellec.me</a>
                                </p>
                            </li>
                            <li>
                                <p>
                                    <i class="icon-globe"></i>www.geraldplusquellec.me
                                </p>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>
<?php includes('partials/footer/classic.phtml'); ?>
    <script type="text/javascript">
      //<![CDATA[
        // Call the google map
        mapInit();
      //]]>
    </script>
