<?php includes('partials/header/classic.phtml'); ?>
<div style="height: 25px;"></div>
<!-- Main Content -->
        <div id="content" role="main">
            <div class="row-fluid">
                <div class="span1">&nbsp;</div>
                <div class="widget span10">
                    <div class="widget-header clearfix">
                        <h3><i class="icon-list"></i>&nbsp;&nbsp;&nbsp;&nbsp;Services</h3>
                    </div>
                    <div class="widget-tabs">
                        <ul class="nav nav-tabs" id="myTab">
                            <li class=""><a href="<?php urlsite(); ?>services/web"><i class="icon-ok"></i> Création site internet</a></li>
                            <li class=""><a href="<?php urlsite(); ?>services/ecommerce"><i class="icon-ok"></i> Commerce en ligne</a></li>
                            <li class="active"><a href="<?php urlsite(); ?>services/content"><i class="icon-ok"></i> Gestionnaire de contenu</a></li>
                            <li class=""><a href="<?php urlsite(); ?>services/refonte"><i class="icon-ok"></i> Refonte de site</a></li>
                            <li class=""><a href="<?php urlsite(); ?>services/vitrine"><i class="icon-ok"></i> Site vitrine</a></li>
                        </ul>
                    </div>
                    <div class="widget-body tab-content">
                        <div class="tab-pane fade active in" id="web">
                            <div class="row-fluid">
                                <p class="span6 align">Je vous propose un système permettant de gérer le contenu de votre site Internet sans aucune notion de programmation ou de graphisme, et ce, à prix concurrentiel. Vous pourrez insérer vous-même le contenu que vous désirez à partir de votre navigateur, que ce soit des images ou du texte. Cet outil très performant permet à quelqu'un n'ayant aucune connaissance en HTML d'effectuer des mises à jour facilement par le biais d'une console d'éditeur texte.</p>
                                <p class="span6"><img alt="" src="<?php urlsite(); ?>assets/img/assets/cms.jpg" /></p>
                            </div>
                            <div class="row-fluid">
                                <p>L'avantage majeur du CMS est qu'il simplifie la modification du contenu. Vous ajouterez, modifierez et supprimerez rapidement vos titres, vos textes et vos images et vos changements pourront être mis en ligne instantanément. Je vous facturerai uniquement les frais initiaux d'installation de l'outil de gestion du contenu qui vous permettra de gérer votre site comme bon vous semble ! Si cette option vous intéresse, <a href="<?php urlsite(); ?>contact">contactez-moi</a> !</p>
                            </div>
                            <div class="row-fluid">
                                <div class="well pricing-table pricing-table-featured span12 pull-left">
                                    <h3>
                                        <span>avantages</span>
                                    </h3>
                                    <ul class="pricing-table-list">
                                        <li>Simplicité d'utilisation</li>
                                        <li>Accessibilité partout grâce à Internet</li>
                                        <li>Interface ergonomique</li>
                                        <li>Réduction des coûts de maintenance</li>
                                        <li>Mises à jour en temps réel</li>
                                        <li>Administration en français et anglais</li>
                                        <li>&Eacute;dition de balises META (titres et mots-clés) pour chacune des pages</li>
                                        <li>Gestionnaire de fichiers multimédia intégré</li>
                                        <li>Accès multi-utilisateur permettant à plusieurs usagers de travailler simultanément</li>
                                    </ul>
                                </div>
                            </div>
                            <div class="row-fluid">
                                <div class="well pricing-table pricing-table-featured span12 pull-left">
                                    <h3>
                                        <span>Fonctionnalités</span>
                                    </h3>
                                    <ul class="pricing-table-list">
                                        <li>Possibilité de créer, d'éditer ou de supprimer les contenus</li>
                                        <li>&Eacute;diteurs WYSIWYG (What you see is what you get)</li>
                                        <li>Gestion de vos images et vos fichiers</li>
                                        <li>Gestion des utilisateurs</li>
                                        <li>Optimisation pour les moteurs de recherche (Meta-tags)</li>
                                        <li>URLs SEF (Search Engine Friendly) permettant une meilleure indexation par les moteurs de recherche</li>
                                        <li>Aisance à copier et à déplacer le contenu entre différentes catégories</li>
                                        <li>Possibilité de mettre le site « hors ligne » lors de maintenance tout en restant visible d'un administrateur</li>
                                        <li>Et plus encore&hellip;</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<?php includes('partials/footer/classic.phtml'); ?>
