<?php includes('partials/header/classic.phtml'); ?>
<div style="height: 25px;"></div>
<!-- Main Content -->
        <div id="content" role="main">
            <div class="row-fluid">
                <div class="span1">&nbsp;</div>
                <div class="widget span10">
                    <div class="widget-header clearfix">
                        <h3><i class="icon-list"></i>&nbsp;&nbsp;&nbsp;&nbsp;Services</h3>
                    </div>
                    <div class="widget-tabs">
                        <ul class="nav nav-tabs" id="myTab">
                            <li class=""><a href="<?php urlsite(); ?>services/web"><i class="icon-ok"></i> Création site internet</a></li>
                            <li class="active"><a href="<?php urlsite(); ?>services/ecommerce"><i class="icon-ok"></i> Commerce en ligne</a></li>
                            <li class=""><a href="<?php urlsite(); ?>services/content"><i class="icon-ok"></i> Gestionnaire de contenu</a></li>
                            <li class=""><a href="<?php urlsite(); ?>services/refonte"><i class="icon-ok"></i> Refonte de site</a></li>
                            <li class=""><a href="<?php urlsite(); ?>services/vitrine"><i class="icon-ok"></i> Site vitrine</a></li>
                        </ul>
                    </div>
                    <div class="widget-body tab-content">
                        <div class="tab-pane fade active in" id="web">
                            <div class="row-fluid">
                                <p class="span6 align">Je peux concevoir votre commerce électronique afin d'élargir votre clientèle et vos ventes. Vous aurez une longueur d'avance sur vos concurrents et serez écologique puisque cela vous évitera d'imprimer de nombreux catalogues ! La vente en ligne est un moyen avant-gardiste de mener des activités commerciales. Il peut être ajouté à un site déjà existant ou encore à un site en cours de conception. Le commerce en ligne couvre chacune des étapes du processus d'achat soit du visionnement à la livraison du produit, en passant par la commande et le paiement. Le commerce électronique est aussi souvent nommé e-commerce, site commercial, boutique en ligne ou commercialisation sur Internet.</p>
                                <p class="span6"><img alt="" src="<?php urlsite(); ?>assets/img/assets/ecommerce.jpg" /></p>
                            </div>
                            <div class="row-fluid">
                                <p>Je suis en mesure d'évaluer le potentiel d'un commerce en ligne pour votre entreprise. Une boutique en ligne offre les avantages de n'être limité par aucune frontière géographique, ni temporelle. N'attendez plus, osez prendre votre place sur le Web et augmentez vos ventes grâce à votre site commercial ! Il est plus que rentable d'investir dans le commerce en ligne si l'on tient compte des retombées d'un tel investissement sur votre chiffre d'affaires.</p>

                                <p>Mon module de commerce en ligne est performant, simple à utiliser et abordable ! Mon rôle est de vous amener à prendre le plein contrôle de votre commerce en ligne. Un panneau de contrôle vous permettra d'administrer, vous-même, la totalité de votre commerce électronique. Facile à gérer, ce panneau de contrôle est un logiciel de commerce en ligne grâce auquel vous pourrez ajouter, changer ou supprimer vos articles, les catégoriser, les associer à des produits vedettes, rétablir vos prix, assurer le suivi de vos commandes et de votre inventaire&hellip; le tout, de façon autonome !</p>

                                <p>L'architecture du site Web, le référencement, l'optimisation et le positionnement sont des éléments clés qui inciteront les internautes à visiter votre commerce en ligne! Enfin, l'outil de gestion des ventes vous permettra d'avoir accès aux statistiques concernant vos ventes, vos produits les plus demandés et vos profits générés par le site commercial. Confiez-moi le soin de vous aider à accroître vos affaires électroniques grâce à mon savoir-faire !</p>
                            </div>
                            <div class="row-fluid">
                                <div class="well pricing-table pricing-table-featured span12 pull-left">
                                    <h3>
                                        <span>quelques fonctionnalités</span>
                                    </h3>
                                    <ul class="pricing-table-list">
                                        <li>Aucun frais mensuel</li>
                                        <li>Design professionnel à l'image de votre entreprise</li>
                                        <li>Nombre illimité de produits et de catégories</li>
                                        <li>Gestionnaire de contenu</li>
                                        <li>Transaction 100 % sécuritaire SSL</li>
                                        <li>Calcul des taxes selon la localisation</li>
                                        <li>Estimation des frais de livraison en temps réel</li>
                                        <li>Gestion de l'inventaire</li>
                                        <li>Optimisé pour les moteurs de recherche</li>
                                        <li>Interface multilingue</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<?php includes('partials/footer/classic.phtml'); ?>
