<?php includes('partials/header/classic.phtml'); ?>

<!-- Main Content -->
        <div id="content" role="main">
            <section class="section alt" id="promo">
                <div class="container">
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="hero-unit">
                                <h1>freelance web depuis 1996</h1>
                                <p>
                                    Au service de sociétés depuis plus de 17 ans, je peux vous accompagner dans vos projets sur les problématiques suivantes :
                                </p>
                                <ul class="icons">
                                    <li>
                                        <i class="icon-bar-chart"></i>Applications web
                                    </li>
                                    <li>
                                        <i class="icon-shopping-cart"></i>E-commerce
                                    </li>
                                    <li>
                                        <i class="icon-globe"></i>Sites vitrine
                                    </li>
                                    <li>
                                        <i class="icon-hdd"></i>Gestion de bases de données
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="span6">
                            <img alt="" src="<?php urlsite(); ?>assets/img/assets/home.jpg" />
                        </div>
                    </div>
                </div>
            </section>
            <section class="section">
                <div class="container">
                    <div class="row-fluid">
                        <div class="span12">
                            <article>
                                <header>
                                    <h2>
                                        philosophie
                                    </h2>
                                </header>
                                <p>
                                    Je prends le temps d'analyser vos besoins et d'établir une stratégie Web conçue pour vous offrir la solution la plus profitable. Mon rôle est de vous alléger la tâche, c'est pourquoi, je vous accompagne dans toutes les étapes de la création Web : l'élaboration du visuel, l'intégration, le développement, la validation du site, la mise en ligne et un référencement optimal.
                                </p>
                            </article>
                        </div>
                    </div>
                </div>
            </section>
        </div>
<?php includes('partials/footer/classic.phtml'); ?>
