<?php includes('partials/header/classic.phtml'); ?>

<!-- Main Content -->
    <div id="content" role="main">
        <section class="section">
            <div class="container">
                <div class="row-fluid">
                    <div class="span12">
                        <article>
                            <header class="pull-center">
                                <h1>
                                    erreur
                                </h1>
                            </header>
                            <p>
                                <h3>Message : </h3>
                                <pre><?php echo $this->error->getMessage(); ?></pre>
                                <h3>Location : </h3>
                                <pre><?php echo $this->error->getFile(); ?> on line <?php echo $this->error->getLine(); ?></pre>
                                <h3>Trace :</h3>
                                <pre><?php echo $this->error->getTraceAsString(); ?>
                            </p>
                        </article>
                    </div>
                </div>
            </div>
        </section>
    </div>

<?php includes('partials/footer/classic.phtml'); ?>
