<?php includes('partials/header/classic.phtml'); ?>

<!-- Main Content -->
    <div id="content" role="main">
      <section class="section alt pull-center" id="promo">
        <div class="container">
          <div class="hero-unit hero-huge hero-404">
            <h1>404</h1>
            <p>
              La page que vous cherchez n'existe pas.
            </p>
          </div>
        </div>
      </section>
      <section class="section">
        <div class="container">
          <div class="row-fluid">
            <div class="span12">
              <article>
                <header class="pull-center">
                  <h2>
                    Que faire
                  </h2>
                </header>
                <p class="pull-center">
                  Retournez sur la page d'
                  <a href="<?php urlsite(); ?>">accueil</a>
                  et retrouvez votre chemin&hellip;
                </p>
              </article>
            </div>
          </div>
        </div>
      </section>
    </div>

<?php includes('partials/footer/classic.phtml'); ?>
