<?php includes('partials/header/classic.phtml'); ?>
<div style="height: 25px;"></div>
<!-- Main Content -->
        <div id="content" role="main">
            <div class="row-fluid">
                <div class="span1">&nbsp;</div>
                <div class="widget span10">
                    <div class="widget-header clearfix">
                        <h3><i class="icon-list"></i>&nbsp;&nbsp;&nbsp;&nbsp;Services</h3>
                    </div>
                    <div class="widget-tabs">
                        <ul class="nav nav-tabs" id="myTab">
                            <li class=""><a href="<?php urlsite(); ?>services/web"><i class="icon-ok"></i> Création site internet</a></li>
                            <li class=""><a href="<?php urlsite(); ?>services/ecommerce"><i class="icon-ok"></i> Commerce en ligne</a></li>
                            <li class=""><a href="<?php urlsite(); ?>services/content"><i class="icon-ok"></i> Gestionnaire de contenu</a></li>
                            <li class="active"><a href="<?php urlsite(); ?>services/refonte"><i class="icon-ok"></i> Refonte de site</a></li>
                            <li class=""><a href="<?php urlsite(); ?>services/vitrine"><i class="icon-ok"></i> Site vitrine</a></li>
                        </ul>
                    </div>
                    <div class="widget-body tab-content">
                        <div class="tab-pane fade active in" id="web">
                            <div class="row-fluid">
                                <p class="span6 align">Vous avez déjà un site Internet, mais souhaitez vous adapter aux nouvelles technologies disponibles pour vous simplifier la vie? En optant pour une refonte de votre site Web, vous rehausserez l'aspect visuel grâce à un design actuel et adapté à votre clientèle en constante évolution. C'est la première impression qui compte !</p>
                                <p class="span6"><img alt="" src="<?php urlsite(); ?>assets/img/assets/refonte.jpg" /></p>
                            </div>
                            <div class="row-fluid">
                                <p>N'oubliez pas qu'un nouveau design permet d'accrocher vos visiteurs, d'où l'importance d'une refonte de site Web. Il s'agit en fait de rafraîchir le site, de lui donner un coup de neuf! Le relookage de votre site Internet est un atout supplémentaire pour fidéliser votre clientèle et donner l'image de marque d'une société dynamique en constante évolution.</p>
                                <p>L'optimisation est un élément fondamental lors d'une refonte de site Internet, car elle englobe le référencement et le positionnement. La refonte permettra à un site déjà existant d'obtenir des visiteurs par le référencement et en étant mieux optimisé par les moteurs de recherche, le site gagnera des positions de tête. Pour que votre site Internet soit dynamique, il est nécessaire d'y apporter des nouveautés, de mettre à jour vos données et d'actualiser son contenu. Un module de gestionnaire de contenu est disponible pour vous permettre de faire ces mises à jour comme bon vous semble.</p>
                                <p>Je vous propose d'améliorer le design et le contenu de votre site par une refonte de site Internet. Avec le service de rédaction Web, vous obtiendrez un meilleur référencement et positionnement. Le tout à un prix très concurrentiel ! N'hésitez pas à <a href="<?php urlsite(); ?>contact">prendre contact</a> pour voir les possibilités qui s'offrent à vous.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<?php includes('partials/footer/classic.phtml'); ?>
