<?php includes('partials/header/classic.phtml'); ?>

<!-- Main Content -->
        <div id="content" role="main">
            <section class="section alt" id="promo">
                <div class="container">
                    <div class="row-fluid">
                        <div class="span6">
                            <div class="hero-unit">
                                <h1>services</h1>
                            </div>
                        </div>
                        <div class="span6">
                            <img alt="" src="<?php urlsite(); ?>assets/img/assets/services.png" />
                        </div>
                    </div>
                </div>
            </section>
            <section class="section">
                <div class="container">
                    <div class="row-fluid">
                        <div class="span12">
                            <article>
                                <header>
                                    <h2>
                                        philosophie
                                    </h2>
                                </header>
                                <p>
                                    &Ecirc;tre présent en ligne n'est pas une fin en soi, mais un moyen d'atteindre vos objectifs. Définir une stratégie cohérente en amont permet de ne pas foncer dans le mur et d'optimiser votre ROI.<br />
                                    Avoir un site ne suffit plus à exister sur Internet, c'est tout un arsenal digital, cohérent et efficace, qu'il faut déployer pour séduire vos prospects.
                                </p>
                                <p>
                                     Internet est un media techniquement exigeant. Conseiller puis mettre en place une solution technique adaptée reste la meilleure garantie de la réussite et de la pérennité d'un projet.<br />
                                     S'y retrouver dans le jargon technique relève de l'impossible pour un néophyte, mais pas de panique, je vais vous aider&hellip;
                                </p>
                            </article>
                        </div>
                    </div>
                </div>
            </section>
        </div>
<?php includes('partials/footer/classic.phtml'); ?>
