<?php includes('partials/header/classic.phtml'); ?>
<div style="height: 25px;"></div>
<!-- Main Content -->
        <div id="content" role="main">
            <div class="row-fluid">
                <div class="span1">&nbsp;</div>
                <div class="widget span10">
                    <div class="widget-header clearfix">
                        <h3><i class="icon-list"></i>&nbsp;&nbsp;&nbsp;&nbsp;Services</h3>
                    </div>
                    <div class="widget-tabs">
                        <ul class="nav nav-tabs" id="myTab">
                            <li class=""><a href="<?php urlsite(); ?>services/web"><i class="icon-ok"></i> Création site internet</a></li>
                            <li class=""><a href="<?php urlsite(); ?>services/ecommerce"><i class="icon-ok"></i> Commerce en ligne</a></li>
                            <li class=""><a href="<?php urlsite(); ?>services/content"><i class="icon-ok"></i> Gestionnaire de contenu</a></li>
                            <li class=""><a href="<?php urlsite(); ?>services/refonte"><i class="icon-ok"></i> Refonte de site</a></li>
                            <li class="active"><a href="<?php urlsite(); ?>services/vitrine"><i class="icon-ok"></i> Site vitrine</a></li>
                        </ul>
                    </div>
                    <div class="widget-body tab-content">
                        <div class="tab-pane fade active in" id="web">
                            <div class="row-fluid">
                                <p class="span6 align">Vous avez besoin de visibilité ? Grâce à un site vitrine, votre entreprise pourra se faire connaître en étant disponible sur Internet. Un site vitrine est, en quelque sorte, une carte de visite ! Il vous permet de devancer vos concurrents et d'élargir votre clientèle.</p>
                                <p class="span6"><img alt="" src="<?php urlsite(); ?>assets/img/assets/vitrine.jpg" /></p>
                            </div>
                            <div class="row-fluid">
                                <p>Le contenu d'un tel site doit être condensé sur une seule page qui contient un nombre limité de renseignements. Les informations essentielles à retrouver dans un site vitrine sont vos coordonnées et vos services en général. C'est un premier pas sur le Web&hellip; Je me ferai un plaisir d'analyser vos besoins et de participer à votre projet, peu importe la taille ou l'ampleur de celui-ci.</p>

                                <p>Le site vitrine sert également à refléter votre image de marque. Il est donc intéressant que le site s'harmonise à l'image de l'entreprise. Cependant, si vous souhaitez repartir à neuf, on peut "revamper" votre look. Si vous êtes en démarrage, nous vous accompagnerons à définir l'image que vous souhaitez projeter.</p>

                                <p>Toutefois, si vous voulez que vos clients puissent découvrir en détail votre entreprise, vos services, vos horaires et vos produits et qu'ils puissent facilement entrer en contact avec vous, vous devez alors envisager la création d'un site complet ! Si cette option vous intéresse, n'hésitez pas à communiquer avec moi. Je serai ravi d'évaluer vos besoins, de répondre à vos questions et de concevoir votre site personnalisé et adapté à vos objectifs !</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<?php includes('partials/footer/classic.phtml'); ?>
