<?php includes('partials/header/classic.phtml'); ?>
<div style="height: 25px;"></div>
<!-- Main Content -->
        <div id="content" role="main">
            <div class="row-fluid">
                <div class="span1">&nbsp;</div>
                <div class="widget span10">
                    <div class="widget-header clearfix">
                        <h3><i class="icon-list"></i>&nbsp;&nbsp;&nbsp;&nbsp;Services</h3>
                    </div>
                    <div class="widget-tabs">
                        <ul class="nav nav-tabs" id="myTab">
                            <li class="active"><a href="<?php urlsite(); ?>services/web"><i class="icon-ok"></i> Création site internet</a></li>
                            <li class=""><a href="<?php urlsite(); ?>services/ecommerce"><i class="icon-ok"></i> Commerce en ligne</a></li>
                            <li class=""><a href="<?php urlsite(); ?>services/content"><i class="icon-ok"></i> Gestionnaire de contenu</a></li>
                            <li class=""><a href="<?php urlsite(); ?>services/refonte"><i class="icon-ok"></i> Refonte de site</a></li>
                            <li class=""><a href="<?php urlsite(); ?>services/vitrine"><i class="icon-ok"></i> Site vitrine</a></li>
                        </ul>
                    </div>
                    <div class="widget-body tab-content">
                        <div class="tab-pane fade active in" id="web">
                            <div class="row-fluid">
                                <p class="span6">Avec mes partenaires, nous prenons le temps d'analyser vos besoins et d'établir une stratégie Web conçue pour vous offrir la solution la plus profitable. Notre rôle est de vous alléger la tâche, c'est pourquoi nous assumons toutes les étapes de la création Web : l'élaboration du visuel, l'intégration, la programmation, la validation du site, la mise en ligne et un référencement optimal.</p>
                                <p class="span6"><img alt="" src="<?php urlsite(); ?>assets/img/assets/web.jpg" /></p>
                            </div>
                            <div class="row-fluid">
                                <p>Un site conçu par notre équipe est synonyme de look, de performance et de rentabilité. Quelques principes de base doivent être pris en considération pour maximiser votre site dont notamment: l'architecture, le contenu et le confort de navigation du site. En effet, lors de la conception d'un site, nous nous orientons dans une optique d'optimisation (référencement et positionnement) ce qui engendre une visibilité et une visite accrue de votre site. Nous enrichissons les contenus, grâce à notre service de rédaction Web. L'approche idéale consiste à combiner et agencer le look, les mesures de visibilité, c'est-à-dire associer le référencement, le positionnement ainsi que les outils statistiques pour obtenir une formule gagnante en marketing sur Internet. Notre engagement est votre réussite sur le Web !</p>

                                <p>Un site doit refléter votre entreprise, c'est une image de marque qui augmente votre notoriété. Laissez-nous vous bâtir votre image Web, nous débordons d'idées rafraîchissantes et audacieuses ! Un partenaire photographe vous permettra de montrer votre entreprise sous ses plus beaux angles. Si vous êtes en lancement d'entreprise, nous proposons également le service de conception graphique pour créer votre image (couleurs et logo).</p>

                                <p>Je reste à l'écoute de vos objectifs pour vous proposer l'idée qui vous convient le mieux, que ce soit pour un site vitrine, une refonte de site ou encore un commerce en ligne. Je suis là pour vous guider pas à pas dans ce projet. Mon expertise en conception Web vous permettra d'avoir l'esprit tranquille, car vous serez assuré d'un site qui se distingue des autres ! Laissez-moi le soin de vous guider dans l'élaboration de votre identité Web afin qu'elle soit à la hauteur de vos attentes !</p>
                            </div>
                            <div class="row-fluid">
                                <div class="well pricing-table pricing-table-featured span12 pull-left">
                                    <h3>
                                        <span>les principales étapes</span>
                                    </h3>
                                    <div class="accordion" id="accordion">
                                        <div class="accordion-group">
                                            <div class="accordion-heading">
                                                <a class="accordion-toggle" data-parent="#accordion" data-toggle="collapse" href="#step_one">
                                                    <strong style="color: #fff;">1. Définir clairement vos objectifs</strong>
                                                </a>
                                            </div>
                                            <div class="accordion-body collapse" id="step_one">
                                                <div class="accordion-inner">
                                                    <ul>
                                                        <li>Présenter vos services, vos produits</li>
                                                        <li>Recruter des employés, faire de la promotion</li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="accordion-heading">
                                                <a class="accordion-toggle" data-parent="#accordion" data-toggle="collapse" href="#step_two">
                                                    <strong style="color: #fff;">2. Déterminer votre cible</strong>
                                                </a>
                                            </div>
                                            <div class="accordion-body collapse" id="step_two">
                                                <div class="accordion-inner">
                                                    <ul>
                                                        <li>Nouveaux clients, employés, fournisseurs</li>
                                                        <li>Langue(s) de rédaction du site</li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="accordion-heading">
                                                <a class="accordion-toggle" data-parent="#accordion" data-toggle="collapse" href="#step_three">
                                                    <strong style="color: #fff;">3. &Eacute;tablir le budget d'élaboration du site</strong>
                                                </a>
                                            </div>
                                            <div class="accordion-body collapse" id="step_three">
                                                <div class="accordion-inner">
                                                    <ul>
                                                        <li>Afin de proposer une solution sur mesure, à la hauteur de votre entreprise</li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="accordion-heading">
                                                <a class="accordion-toggle" data-parent="#accordion" data-toggle="collapse" href="#step_four">
                                                    <strong style="color: #fff;">4. Décrire une arborescence fonctionnelle</strong>
                                                </a>
                                            </div>
                                            <div class="accordion-body collapse" id="step_four">
                                                <div class="accordion-inner">
                                                    <ul>
                                                        <li>Pour élaborer les sections du site selon une accessibilité Web</li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="accordion-heading">
                                                <a class="accordion-toggle" data-parent="#accordion" data-toggle="collapse" href="#step_five">
                                                    <strong style="color: #fff;">5. Concevoir une maquette papier du site selon vos besoins</strong>
                                                </a>
                                            </div>
                                            <div class="accordion-body collapse" id="step_five">
                                                <div class="accordion-inner">
                                                    <ul>
                                                        <li>Sert à définir le « look » de votre site sur le plan visuel</li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="accordion-heading">
                                                <a class="accordion-toggle" data-parent="#accordion" data-toggle="collapse" href="#step_six">
                                                    <strong style="color: #fff;">6. Créer la maquette numérique</strong>
                                                </a>
                                            </div>
                                            <div class="accordion-body collapse" id="step_six">
                                                <div class="accordion-inner">
                                                    <ul>
                                                        <li>Pour déterminer l'imagerie finale du site</li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="accordion-heading">
                                                <a class="accordion-toggle" data-parent="#accordion" data-toggle="collapse" href="#step_seven">
                                                    <strong style="color: #fff;">7. Rédiger le contenu textuel Web</strong>
                                                </a>
                                            </div>
                                            <div class="accordion-body collapse" id="step_seven">
                                                <div class="accordion-inner">
                                                    <ul>
                                                        <li>Pour un site Web, le contenu doit être préférablement court et concis</li>
                                                        <li>Je propose un service de rédaction Web et de traduction</li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="accordion-heading">
                                                <a class="accordion-toggle" data-parent="#accordion" data-toggle="collapse" href="#step_eight">
                                                    <strong style="color: #fff;">8. Intégrer les textes selon une optimisation pour obtenir les meilleures positions</strong>
                                                </a>
                                            </div>
                                            <div class="accordion-body collapse" id="step_eight">
                                                <div class="accordion-inner">
                                                    <ul>
                                                        <li>Analyse des mots-clés habituellement utilisés par les cibles</li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="accordion-heading">
                                                <a class="accordion-toggle" data-parent="#accordion" data-toggle="collapse" href="#step_nine">
                                                    <strong style="color: #fff;">9. Validation et lancement du site</strong>
                                                </a>
                                            </div>
                                            <div class="accordion-body collapse" id="step_nine">
                                                <div class="accordion-inner">
                                                    <ul>
                                                        <li>Hébergement sur nos serveurs sécurisés (Québec &amp; France)</li>
                                                        <li>Dernières modifications avant la mise en ligne</li>
                                                    </ul>
                                                </div>
                                            </div>
                                            <div class="accordion-heading">
                                                <a class="accordion-toggle" data-parent="#accordion" data-toggle="collapse" href="#step_ten">
                                                    <strong style="color: #fff;">10. Suivi de performance</strong>
                                                </a>
                                            </div>
                                            <div class="accordion-body collapse" id="step_ten">
                                                <div class="accordion-inner">
                                                    <ul>
                                                        <li>Analyse statistique des comportements de vos visiteurs</li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
<?php includes('partials/footer/classic.phtml'); ?>
